version: '3.4'

services:
  strava-reg:
    build: .
    environment:
      - STRAVA_CLIENT_ID=''
      - STRAVA_CLIENT_SECRET=''
      - PORT=3000
      - CALL_BACK_URL=''
      - AUTH_DATA_FILE=/data
    volumes:
      - ./data:/data
    ports:
      - 8090:3000