version: '3.4'

services:
  strava-intania-reg:
    build: .
    environment:
      - STRAVA_CLIENT_ID=${INT_STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${INT_STRAVA_CLIENT_SECRET}
      - CALL_BACK_URL=${INT_CALL_BACK_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVICE_TYPE=intania
    volumes:
      - .:/icmm-strava-reg
    ports:
      - 8090:3000
    
  strava-foundation-reg:
    build: .
    environment:
      - STRAVA_CLIENT_ID=${F5_STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${F5_STRAVA_CLIENT_SECRET}
      - CALL_BACK_URL=${F5_CALL_BACK_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVICE_TYPE=foundation
    volumes:
      - .:/icmm-strava-reg
    ports:
      - 8091:3000
